# Generated by Django 6.0 on 2025-12-10 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва клініки')),
                ('description', models.TextField(verbose_name='Опис')),
                ('address', models.CharField(max_length=300, verbose_name='Адреса')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Довгота')),
                ('working_hours_start', models.TimeField(verbose_name='Початок роботи')),
                ('working_hours_end', models.TimeField(verbose_name='Кінець роботи')),
                ('working_days', models.CharField(default='Пн-Пт', max_length=100, verbose_name='Робочі дні')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clinics/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клініка',
                'verbose_name_plural': 'Клініки',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('therapy', 'Терапія'), ('surgery', 'Хірургія'), ('vaccination', 'Вакцинація'), ('dental', 'Стоматологія'), ('grooming', 'Догляд за тваринами'), ('lab', 'Лабораторні дослідження'), ('emergency', 'Екстрена допомога')], max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Спеціалізація клініки',
                'verbose_name_plural': 'Спеціалізації клінік',
                'unique_together': {('clinic', 'specialization')},
            },
        ),
    ]
