# Generated by Django 6.0 on 2025-12-10 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('service_type', models.CharField(choices=[('consultation', 'Консультація'), ('vaccination', 'Вакцинація'), ('surgery', 'Хірургія'), ('dental', 'Стоматологія'), ('grooming', 'Догляд'), ('lab_test', 'Лабораторні тести'), ('xray', 'Рентген'), ('ultrasound', 'УЗД'), ('therapy', 'Терапія'), ('emergency', 'Екстрена допомога')], max_length=50, verbose_name='Тип послуги')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна (грн)')),
                ('duration_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тривалість (хв)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['service_type', 'name'],
            },
        ),
    ]
