# Generated by Django 6.0 on 2025-12-10 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Схвалено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Відгук про лікаря',
                'verbose_name_plural': 'Відгуки про лікарів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Схвалено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Відгук про клініку',
                'verbose_name_plural': 'Відгуки про клініки',
                'ordering': ['-created_at'],
            },
        ),
    ]
