# Generated by Django 6.0 on 2025-12-12 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0002_initial'),
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='doctorreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='clinicreview',
            unique_together={('clinic', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorreview',
            unique_together={('doctor', 'user')},
        ),
        migrations.AlterField(
            model_name='clinicreview',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clinicreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctorreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.RemoveField(
            model_name='clinicreview',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='doctorreview',
            name='is_approved',
        ),
    ]
