# Generated by Django 6.0 on 2025-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Дата прийому')),
                ('appointment_time', models.TimeField(verbose_name='Час прийому')),
                ('status', models.CharField(choices=[('pending', 'Очікується'), ('confirmed', 'Підтверджено'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID події в Google Calendar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
